name       : python-keyring
version    : 17.1.1
release    : 4
source     :
    - https://pypi.io/packages/source/k/keyring/keyring-17.1.1.tar.gz : 8f683fa6c8886da58b28c7d8e3819b1a4bf193741888e33a6e00944b673a22cf
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - pkgconfig(python3)
    - python-entrypoints
    - python-pytest-flake8
    - python-secretstorage
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-entrypoints
    - python-secretstorage
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
