name       : python-keyring
version    : 11.0.0
release    : 3
source     :
    - https://pypi.python.org/packages/5e/f8/ac0b545c716ed7bab54d11669328e34a6f1eb4a5d8b188d443a7b234861f/keyring-11.0.0.tar.gz : b4607520a7c97be96be4ddc00f4b9dac65f47a45af4b4cd13ed5a8879641d646
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - pkgconfig(python3)
    - python-pytest
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-secretstorage
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    pushd $PKG_BUILD_DIR/py2build
        PYTHONPATH=$PWD py.test
    popd
    pushd $PKG_BUILD_DIR/py3build
        PYTHONPATH=$PWD py.test3
    popd
