name       : python-keyring
version    : 23.11.0
release    : 18
source     :
    - https://files.pythonhosted.org/packages/source/k/keyring/keyring-23.11.0.tar.gz : ad192263e2cdd5f12875dedc2da13534359a7e760e77f8d04b50968a821c2361
homepage   : https://github.com/jaraco/keyring
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - python-build
    - python-importlib-metadata
    - python-installer
    - python-jaraco.classes     # check
    - python-packaging
    - python-pytest-cov         # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-importlib-metadata
    - python-jaraco.classes
    - python-secretstorage
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
