name       : python-keyring
version    : 23.7.0
release    : 16
source     :
    - https://files.pythonhosted.org/packages/source/k/keyring/keyring-23.7.0.tar.gz : 782e1cd1132e91bf459fcd243bcf25b326015c1ac0b198e4408f91fa6791062b
homepage   : https://github.com/jaraco/keyring
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-pytest-cov         # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-secretstorage
setup      : |
    # We don't have pytest-black and pytest-mypy in the repo
    sed -i 's/ --black//; s/ --mypy//' pytest.ini

    %python3_setup
install    : |
    %python3_install
check      : |
    # Upstream issue: https://github.com/jaraco/keyring/issues/526
    %python3_test pytest3 --deselect tests/test_packaging.py::test_entry_point
