name       : python-keyring
version    : 23.5.1
release    : 15
source     :
    - https://files.pythonhosted.org/packages/source/k/keyring/keyring-23.5.1.tar.gz : dee502cdf18a98211bef428eea11456a33c00718b2f08524fd5727c7f424bffd
homepage   : https://github.com/jaraco/keyring
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - python-build
    - python-importlib-metadata # check
    - python-installer
    - python-packaging
    - python-pytest-cov         # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-importlib-metadata
    - python-secretstorage
setup      : |
    # We don't have pytest-black and pytest-mypy in the repo
    sed -i 's/ --black//; s/ --mypy//' pytest.ini

    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
