name       : python-keyring
version    : 23.8.2
release    : 17
source     :
    - https://files.pythonhosted.org/packages/source/k/keyring/keyring-23.8.2.tar.gz : 0d9973f8891850f1ade5f26aafd06bb16865fbbae3fc56b0defb6a14a2624003
homepage   : https://github.com/jaraco/keyring
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - python-build
    - python-installer
    - python-packaging
    - python-pytest-cov         # check
    - python-setuptools-scm
    - python-wheel
rundeps    :
    - python-secretstorage
setup      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    # Upstream issue: https://github.com/jaraco/keyring/issues/526
    %python3_test pytest3 --deselect tests/test_packaging.py::test_entry_point
