name       : python-keyring
version    : 18.0.1
release    : 5
source     :
    - https://files.pythonhosted.org/packages/5e/4a/d1e3f7284b00d7d59dfa436a773a02cb360378ae6f7f225c587b39cc5d2f/keyring-18.0.1.tar.gz : 67d6cc0132bd77922725fae9f18366bb314fd8f95ff4d323a4df41890a96a838
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - pkgconfig(python3)
    - python-entrypoints
    - python-pytest-flake8
    - python-secretstorage
    - python-setuptools
    - python-setuptools-scm
rundeps    :
    - python-entrypoints
    - python-secretstorage
setup      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
check      : |
    %python_test py.test
    %python3_test py.test3
