name       : python-keyring
version    : 21.4.0
release    : 8
source     :
    - https://files.pythonhosted.org/packages/source/k/keyring/keyring-21.4.0.tar.gz : 9aeadd006a852b78f4b4ef7c7556c2774d2432bbef8ee538a3e9089ac8b11466
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - pkgconfig(python3)
    - python-entrypoints
    - python-pytest-cov
    - python-pytest-flake8
    - python-secretstorage
    - python-setuptools-scm
    - python-toml
rundeps    :
    - python-entrypoints
    - python-importlib-metadata
    - python-secretstorage
setup      : |
    # We don't have pytest-black and pytest-mypy in the repo
    sed -i 's/ --black//; s/ --mypy//' pytest.ini

    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
