name       : python-keyring
version    : 22.0.1
release    : 10
source     :
    - https://files.pythonhosted.org/packages/source/k/keyring/keyring-22.0.1.tar.gz : 9acb3e1452edbb7544822b12fd25459078769e560fa51f418b6d00afaa6178df
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - pkgconfig(python3)
    - python-entrypoints
    - python-pytest-cov
    - python-pytest-flake8
    - python-secretstorage
    - python-setuptools-scm
    - python-toml
rundeps    :
    - python-entrypoints
    - python-importlib-metadata
    - python-secretstorage
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-versioning.patch

    # We don't have pytest-black and pytest-mypy in the repo
    sed -i 's/ --black//; s/ --mypy//' pytest.ini

    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
    # No thanks
    rm -r $installdir/usr/lib/python%python3_version%/site-packages/keyring/backends/macOS/
