name       : python-keyring
version    : 22.2.0
release    : 12
source     :
    - https://files.pythonhosted.org/packages/source/k/keyring/keyring-22.2.0.tar.gz : c73c66c4ca89bee6a233b1638e1d2f5bcba4da35f8713ad4f98decc46e64cccd
license    :
    - MIT
    - Python-2.0
component  : programming.python
summary    : Python system keyring module
description: |
    The python keyring lib provides and easy way to access the system keyring service from python.  It can be used in any application that needs safe password storage.
builddeps  :
    - pkgconfig(python3)
    - python-entrypoints
    - python-pytest-cov
    - python-pytest-flake8
    - python-secretstorage
    - python-setuptools-scm
    - python-toml
rundeps    :
    - python-entrypoints
    - python-importlib-metadata
    - python-secretstorage
setup      : |
    %patch -p1 < $pkgfiles/0001-Fix-versioning.patch

    # We don't have pytest-black and pytest-mypy in the repo
    sed -i 's/ --black//; s/ --mypy//' pytest.ini

    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test py.test3
